/* WRITE A PROGRAM TO READ INFORMATION OF 10 STUDENTS AND DISPLAY THE INFORMATION OF THOSE STUDENTS WHOSE MARKS ARE 
GREATER THAN 500 (PASSING ARRAY OF STRUCTURE INTO FUNCTION)*/
#include<stdio.h>
struct student